import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from "./Components/Navbar/index"
import Footer from "./Components/Footer/index"

import tw from "tailwind-styled-components"

const Container = tw.div`
     w-full 
     px-16 
     py-12
`;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Navbar />
        <Container>
          {children}
        </Container>
        <Footer />
      </body>

    </html>
  )
}
